name: alikala
description: online store application like Digikala.com
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  footprint: ^1.1.3
  intl:
  intl_translation:
  flutter_bloc: ^6.0.5
  connectivity: ^0.4.9+3
  shared_preferences: ^0.5.12
  sailor: ^0.7.1
  freezed_annotation: ^0.11.0+1
  json_annotation: ^3.0.1
  fluttertoast: ^7.1.1
  injectable: ^1.0.4
  get_it: ^4.0.4
  url_launcher: ^5.7.2
  shamsi_date: ^0.9.1
  tuple: ^1.0.3
  dio: ^3.0.10
  auto_size_text: ^2.1.0
  carousel_slider: ^2.3.1
  flutter_custom_clippers: ^1.1.2
  cached_network_image: ^2.3.3

  explode_view: ^1.0.4
  #  permission_handler: ^5.0.1+1
  #  moor: ^3.3.1
  #  sqlite3_flutter_libs: ^0.2.0
  confetti: ^0.5.4+1
  flutter_group_sliver: ^0.0.2
  device_preview: ^0.4.8
  path_provider:
  path:

  ################################# icons ##########################################
  cupertino_icons: ^1.0.0
  feather_icons_flutter: ^4.7.4 # https://feathericons.com/
#  ionicons: ^0.0.3 #https://ionicons.com/
#  community_material_icon: ^5.4.55 #https://materialdesignicons.com/
#  font_awesome_flutter: ^8.5.0 # https://fontawesome.com/icons
#  line_icons: ^0.2.0 # https://icons8.com/line-awesome

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^1.0.4
  #  moor_generator: ^3.3.1
  build_runner: ^1.10.1
  mockito: ^4.1.1
  freezed: ^0.11.5
  # preview: ^0.0.8
  json_serializable: ^3.4.1
  flutter_launcher_icons: ^0.7.2
  test: ^1.15.2
  bloc_test: ^7.0.0

dependency_overrides:
  freezed_annotation: ^0.11.0+1

#dependency_overrides:
#  analyzer: '0.39.14'

# #just run -> flutter pub run flutter_launcher_icons:main
# flutter_icons:
#   #    image_path: "assets/images/icon-128x128.png"
#   image_path_android: "assets/icons/icon_legacy.png"
#   image_path_ios: "assets/icons/icon_legacy_ios.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
# #  adaptive_icon_background: "assets/icons/icon_back.png" # only available for Android 8.0 devices and above
# #  adaptive_icon_foreground: "assets/icons/icon_front.png" # only available for Android 8.0 devices and above

# run -> fluttergen -c example/pubspec.yaml
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 120 # Optional (default: 80)

#  integrations:
#    flutter_svg: true

#  colors:
#    inputs:
#      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/empty_cart.png
    - assets/images/image_placeholder.png

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-Black.ttf
          weight: 900
    - family: Estedad-FD
      fonts:
        - asset: assets/fonts/Estedad-FD-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-FD-Black.ttf
          weight: 900
