name: alikala
description: online store application like Digikala.com
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl: ^0.18.0
  connectivity: ^3.0.6
  shared_preferences: ^2.0.16
  fluttertoast: ^8.1.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  url_launcher: ^6.0.9
  shamsi_date: ^1.0.1
  tuple: ^2.0.0
  dio: ^4.0.6
  carousel_slider: ^4.0.0
  flutter_custom_clippers: ^2.0.0
  cached_network_image: ^3.2.3
  auto_route: ^5.0.4
  equatable: ^2.0.3
  flutter_riverpod: ^2.3.4
  # crystalline:
  # path: ../crystalline/packages/crystalline/
  flutter_crystalline:
    path: ../crystalline/packages/flutter_crystalline/
  faker:
    git: https://github.com/easazade/faker.git # TODO: use faker_x
  feather_icons_flutter:
    git: git@github.com:easazade/feather_icons_flutter.git
  cupertino_icons: ^1.0.3
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.4.0
  build_runner: ^2.0.6
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  crystalline:
    path: ../crystalline/packages/crystalline/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 120 # Optional (default: 80)

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/splash_logo_accent_color.png
    - assets/images/empty_cart.png
    - assets/images/image_placeholder.png
    - assets/images/coin_dash.png
    - assets/images/retry.png

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-Black.ttf
          weight: 900
    - family: Estedad-FD
      fonts:
        - asset: assets/fonts/Estedad-FD-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-FD-Black.ttf
          weight: 900
    - family: Canilari
      fonts:
        - asset: assets/fonts/Canilari-ProBold.ttf
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf

flutter_intl:
  # main_locale: fa_IR
  enabled: true
