name: alikala
description: online store application like Digikala.com
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # footprint: ^1.1.3
  flutter_lints: ^1.0.4  
  intl: ^0.17.0
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  provider: ^6.0.1 # TODO: remove this 
  # sailor: ^0.7.1
  # freezed_annotation: ^0.14.3
  # json_annotation: ^4.1.0
  fluttertoast: ^8.0.7
  injectable: ^1.4.1
  get_it: ^7.2.0
  url_launcher: ^6.0.9
  shamsi_date: ^0.15.0
  tuple: ^2.0.0
  dio: ^4.0.0
  carousel_slider: ^4.0.0
  flutter_custom_clippers: ^2.0.0
  cached_network_image: ^3.1.0
  flushbar: ^1.10.4 # use flash package insread if you have the time
  auto_route: ^2.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  # explode_view: ^1.0.4
  #  permission_handler: ^5.0.1+1
  #  moor: ^3.3.1
  #  sqlite3_flutter_libs: ^0.2.0
  # confetti: ^0.6.0-nullsafety
  # flutter_group_sliver: ^0.0.2
  # flutter_verification_code: ^0.2.1
  # device_preview: ^0.4.8
  faker:
    git: https://github.com/easazade/faker.git
#  adaptive_dialog: ^0.9.0+1
  path_provider:
  path:

  ################################# icons ##########################################
  cupertino_icons: ^1.0.3
  feather_icons_flutter: 
    git: git@github.com:easazade/feather_icons_flutter.git
#  ionicons: ^0.0.3 #https://ionicons.com/
#  community_material_icon: ^5.4.55 #https://materialdesignicons.com/
#  font_awesome_flutter: ^8.5.0 # https://fontawesome.com/icons
#  line_icons: ^0.2.0 # https://icons8.com/line-awesome

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.4.0
  # injectable_generator: ^1.0.4
  #  moor_generator: ^3.3.1
  build_runner: ^2.0.6
  auto_route_generator: ^2.1.0
  # mockito: ^4.1.1
  # freezed: ^0.14.3
  # preview: ^0.0.8
  flutter_launcher_icons: ^0.9.0
  # test: ^1.17.10

  

#dependency_overrides:
#  analyzer: '0.39.14'

# #just run -> flutter pub run flutter_launcher_icons:main
# flutter_icons:
#   #    image_path: "assets/images/icon-128x128.png"
#   image_path_android: "assets/icons/icon_legacy.png"
#   image_path_ios: "assets/icons/icon_legacy_ios.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
# #  adaptive_icon_background: "assets/icons/icon_back.png" # only available for Android 8.0 devices and above
# #  adaptive_icon_foreground: "assets/icons/icon_front.png" # only available for Android 8.0 devices and above

# run -> fluttergen -c example/pubspec.yaml
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 120 # Optional (default: 80)

#  integrations:
#    flutter_svg: true

#  colors:
#    inputs:
#      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png
    - assets/images/splash_logo_accent_color.png
    - assets/images/empty_cart.png
    - assets/images/image_placeholder.png
    - assets/images/coin_dash.png
    - assets/images/retry.png

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-Black.ttf
          weight: 900
    - family: Estedad-FD
      fonts:
        - asset: assets/fonts/Estedad-FD-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-FD-Black.ttf
          weight: 900
    - family: Canilari
      fonts:
        - asset: assets/fonts/Canilari-ProBold.ttf
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf

flutter_intl:
  # main_locale: fa_IR
  enabled: true

